name: CI
on: [push]
jobs:
  npm:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install ligo via NPM
        run: npm i -g ligolang@windows --verbose
      - run: echo "${HOME}/AppData/Roaming/npm" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        name: Add ligo binary to $PATH
      - run: echo $env:PATH
      - run: yarn
        name: Installing dependencies
      - run: yarn jest -- npm
        name: Running npm test
        env:
          DEBUG: resolveCmd

  yarn:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install ligo via Yarn
        run: yarn global add ligolang@windows --verbose
      - run: echo "C:\\Users\\runneradmin\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\ligolang\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        name: Add ligo binary to $PATH
      - run: echo $env:PATH
      - run: yarn
        name: Installing dependencies
      - run: yarn jest -- yarn
        name: Running yarn test

